site_name: SzakGyak
repo_url: https://github.com/JanosSandor2002/SzakGyak

nav:
  - "Project Terv":
      - project-plan/index.md
      - project-plan/members.md
      - project-plan/development.md
      - project-plan/tools.md
      - project-plan/components.md
      - project-plan/referencies.md
      - project-plan/tests.md
      - project-plan/gannt.md
  - "Dokumentáció":
      - documentation/vision.md
      - documentation/srs.md
      - documentation/analysismodel.md
      - documentation/systemarch.md
  - "Munkanapló": "https://docs.google.com/spreadsheets/d/1jSlDk9d3kgoSkNY78S58bChsSggCFRqs5fNXPh3aXEc"
  - "Prototípus":
      - prototypes/game.md

plugins:
  - search
  - literate-nav
  - enumerate-headings:
      restart_increment_after:
        - documentation/vision.md

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny

markdown_extensions:
  - smarty
  - toc:
      toc_depth: 3
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
